# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.leet_code_import_request import LeetCodeImportRequest

class TestLeetCodeImportRequest(unittest.TestCase):
    """LeetCodeImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeetCodeImportRequest:
        """Test LeetCodeImportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeetCodeImportRequest`
        """
        model = LeetCodeImportRequest()
        if include_optional:
            return LeetCodeImportRequest(
                external_id = '',
                title = '',
                description = '',
                difficulty = '',
                constraints = '',
                starter_codes = {
                    'key' : ''
                    },
                testcases = [
                    code_review_api_client.models.testcase_dto.TestcaseDto(
                        input = '', 
                        expected_output = '', 
                        is_hidden = True, 
                        explanation = '', )
                    ],
                similar_question_ids = [
                    ''
                    ]
            )
        else:
            return LeetCodeImportRequest(
        )
        """

    def testLeetCodeImportRequest(self):
        """Test LeetCodeImportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
