# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.api_response_list_problem_response import ApiResponseListProblemResponse

class TestApiResponseListProblemResponse(unittest.TestCase):
    """ApiResponseListProblemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseListProblemResponse:
        """Test ApiResponseListProblemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseListProblemResponse`
        """
        model = ApiResponseListProblemResponse()
        if include_optional:
            return ApiResponseListProblemResponse(
                success = True,
                message = '',
                data = [
                    code_review_api_client.models.problem_response.ProblemResponse(
                        id = '', 
                        external_id = '', 
                        title = '', 
                        description = '', 
                        difficulty = '', 
                        problem_constraint = '', 
                        type = 'MANUAL', 
                        function_skeletons = {
                            'key' : ''
                            }, 
                        testcases = [
                            code_review_api_client.models.testcase_response.TestcaseResponse(
                                id = '', 
                                problem_id = '', 
                                input = '', 
                                expected_output = '', 
                                is_hidden = True, 
                                explanation = '', )
                            ], 
                        similar_question_ids = [
                            ''
                            ], )
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseListProblemResponse(
        )
        """

    def testApiResponseListProblemResponse(self):
        """Test ApiResponseListProblemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
