# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pydantic import ValidationError

from code_review_api_client.models.problem_response import ProblemResponse

class TestProblemResponse(unittest.TestCase):
    """ProblemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemResponse:
        """Test ProblemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemResponse`
        """
        model = ProblemResponse()
        if include_optional:
            return ProblemResponse(
                id = '',
                description = '',
                problem_constraint = ''
            )
        else:
            return ProblemResponse(
        )
        """

    def testProblemResponse(self):
        """Test ProblemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

    def test_type_accepts_library_and_class(self):
        library_problem = ProblemResponse(type="LIBRARY")
        class_problem = ProblemResponse(type="CLASS")

        self.assertEqual("LIBRARY", library_problem.type)
        self.assertEqual("CLASS", class_problem.type)

    def test_type_rejects_legacy_values(self):
        with self.assertRaises(ValidationError):
            ProblemResponse(type="LEETCODE")

if __name__ == '__main__':
    unittest.main()
