# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.class_overview_response import ClassOverviewResponse

class TestClassOverviewResponse(unittest.TestCase):
    """ClassOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassOverviewResponse:
        """Test ClassOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassOverviewResponse`
        """
        model = ClassOverviewResponse()
        if include_optional:
            return ClassOverviewResponse(
                id = '',
                name = '',
                instructor_name = '',
                enrolled_students_count = 56,
                status = 'IN_PROGRESS',
                image_url = ''
            )
        else:
            return ClassOverviewResponse(
        )
        """

    def testClassOverviewResponse(self):
        """Test ClassOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
