# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.api_response_run_code_response import ApiResponseRunCodeResponse

class TestApiResponseRunCodeResponse(unittest.TestCase):
    """ApiResponseRunCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseRunCodeResponse:
        """Test ApiResponseRunCodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseRunCodeResponse`
        """
        model = ApiResponseRunCodeResponse()
        if include_optional:
            return ApiResponseRunCodeResponse(
                success = True,
                message = '',
                data = code_review_api_client.models.run_code_response.RunCodeResponse(
                    status = 'ACCEPTED', 
                    testcases = [
                        code_review_api_client.models.testcase_result.TestcaseResult(
                            index = 56, 
                            input = '', 
                            expected_output = '', 
                            output = '', 
                            error = '', 
                            status = 'ACCEPTED', 
                            runtime = 56, )
                        ], 
                    passed_testcases = 56, 
                    total_testcases = 56, ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseRunCodeResponse(
        )
        """

    def testApiResponseRunCodeResponse(self):
        """Test ApiResponseRunCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
