# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.api.testcase_api import TestcaseApi


class TestTestcaseApi(unittest.TestCase):
    """TestcaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestcaseApi()

    def tearDown(self) -> None:
        pass

    def test_create_testcase(self) -> None:
        """Test case for create_testcase

        Create a testcase for a problem
        """
        pass

    def test_get_testcases(self) -> None:
        """Test case for get_testcases

        Get testcases by problem ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
