# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.submission_detail_response import SubmissionDetailResponse

class TestSubmissionDetailResponse(unittest.TestCase):
    """SubmissionDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionDetailResponse:
        """Test SubmissionDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionDetailResponse`
        """
        model = SubmissionDetailResponse()
        if include_optional:
            return SubmissionDetailResponse(
                submission_id = '',
                problem_title = '',
                problem_description = '',
                score = '',
                difficulty = '',
                code = '',
                language = '',
                status = '',
                testcases = [
                    code_review_api_client.models.testcase_response.TestcaseResponse(
                        id = '', 
                        problem_id = '', 
                        input = '', 
                        expected_output = '', 
                        explanation = '', 
                        sample = True, )
                    ]
            )
        else:
            return SubmissionDetailResponse(
        )
        """

    def testSubmissionDetailResponse(self):
        """Test SubmissionDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
