# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.api.class_api import ClassApi


class TestClassApi(unittest.TestCase):
    """ClassApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClassApi()

    def tearDown(self) -> None:
        pass

    def test_add_student(self) -> None:
        """Test case for add_student

        Add student to class
        """
        pass

    def test_class_detail(self) -> None:
        """Test case for class_detail

        Get class detail
        """
        pass

    def test_create_class(self) -> None:
        """Test case for create_class

        Create a new class
        """
        pass

    def test_my_classes(self) -> None:
        """Test case for my_classes

        Get classes of current user
        """
        pass

    def test_remove_student(self) -> None:
        """Test case for remove_student

        Remove student from class
        """
        pass


if __name__ == '__main__':
    unittest.main()
