# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.api.review_api import ReviewApi


class TestReviewApi(unittest.TestCase):
    """ReviewApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReviewApi()

    def tearDown(self) -> None:
        pass

    def test_history(self) -> None:
        """Test case for history

        Get review history of a submission
        """
        pass

    def test_review(self) -> None:
        """Test case for review

        Review a submission (AI code review)
        """
        pass


if __name__ == '__main__':
    unittest.main()
