# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.api.execution_api import ExecutionApi


class TestExecutionApi(unittest.TestCase):
    """ExecutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExecutionApi()

    def tearDown(self) -> None:
        pass

    def test_judge(self) -> None:
        """Test case for judge

        Run and judge code against testcases
        """
        pass

    def test_run(self) -> None:
        """Test case for run

        Run code without judging
        """
        pass


if __name__ == '__main__':
    unittest.main()
