# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.testcase_dto import TestcaseDto

class TestTestcaseDto(unittest.TestCase):
    """TestcaseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestcaseDto:
        """Test TestcaseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestcaseDto`
        """
        model = TestcaseDto()
        if include_optional:
            return TestcaseDto(
                input = '',
                expected_output = '',
                is_hidden = True,
                explanation = ''
            )
        else:
            return TestcaseDto(
        )
        """

    def testTestcaseDto(self):
        """Test TestcaseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
