# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.models.problem_request import ProblemRequest

class TestProblemRequest(unittest.TestCase):
    """ProblemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemRequest:
        """Test ProblemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemRequest`
        """
        model = ProblemRequest()
        if include_optional:
            return ProblemRequest(
                description = '',
                testcases = [
                    code_review_api_client.models.testcase_request.TestcaseRequest(
                        input = '', 
                        expected_output = '', 
                        explanation = '', 
                        sample = True, )
                    ]
            )
        else:
            return ProblemRequest(
        )
        """

    def testProblemRequest(self):
        """Test ProblemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
