# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_api_client.api.topic_api import TopicApi


class TestTopicApi(unittest.TestCase):
    """TopicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TopicApi()

    def tearDown(self) -> None:
        pass

    def test_create_topic(self) -> None:
        """Test case for create_topic

        Create a new topic
        """
        pass

    def test_get_topic_detail(self) -> None:
        """Test case for get_topic_detail

        Get topic detail (assignments + documents)
        """
        pass

    def test_get_topics_by_class(self) -> None:
        """Test case for get_topics_by_class

        Get topics overview by classId
        """
        pass


if __name__ == '__main__':
    unittest.main()
