services:
  jobe:
    image: trampgeek/jobeinabox
    container_name: jobe-server
    ports:
      - "4000:80"
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    # build: code-review-fe/
    image: dcberr/datn-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - app-network

  review-agent:
    build: review-agent/
    container_name: review-agent
    ports:
      - "8000:8000"
    environment:
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
    restart: always
    networks:
      - app-network

  backend:
    build: code-review-backend/
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy  
      jobe:
        condition: service_started
      minio:
        condition: service_started
    env_file:
      - .env
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - APPLICATION_URL=${APPLICATION_URL}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

      - CLIENT_SECRET=${CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - CLIENT_ID=${CLIENT_ID}

      - JOBE_URL=http://jobe-server/jobe/index.php/restapi
      - REVIEW_AGENT_URL=http://review-agent:8000/api/v1/review_code

      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
  postgres-data: