# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubmissionOverviewResponse(BaseModel):
    """
    SubmissionOverviewResponse
    """ # noqa: E501
    submission_id: Optional[UUID] = Field(default=None, alias="submissionId")
    assignment_title: Optional[StrictStr] = Field(default=None, alias="assignmentTitle")
    problem_title: Optional[StrictStr] = Field(default=None, alias="problemTitle")
    score: Optional[StrictStr] = None
    difficulty: Optional[StrictStr] = None
    deadline: Optional[datetime] = None
    status: Optional[StrictStr] = None
    submitted_at: Optional[datetime] = Field(default=None, alias="submittedAt")
    student_name: Optional[StrictStr] = Field(default=None, alias="studentName")
    __properties: ClassVar[List[str]] = ["submissionId", "assignmentTitle", "problemTitle", "score", "difficulty", "deadline", "status", "submittedAt", "studentName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubmissionOverviewResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubmissionOverviewResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "submissionId": obj.get("submissionId"),
            "assignmentTitle": obj.get("assignmentTitle"),
            "problemTitle": obj.get("problemTitle"),
            "score": obj.get("score"),
            "difficulty": obj.get("difficulty"),
            "deadline": obj.get("deadline"),
            "status": obj.get("status"),
            "submittedAt": obj.get("submittedAt"),
            "studentName": obj.get("studentName")
        })
        return _obj


