# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExerciseRelation(BaseModel):
    """
    ExerciseRelation
    """ # noqa: E501
    exercise_id: StrictStr
    related_exercise_id: StrictStr
    weight: Optional[Union[StrictFloat, StrictInt]] = 1.0
    relation_type: Optional[StrictStr] = ''
    target_concept_id: Optional[StrictStr] = ''
    shared_concept_ids: Optional[List[StrictStr]] = None
    difficulty_gap: Optional[Union[StrictFloat, StrictInt]] = 0.0
    progression_score: Optional[Union[StrictFloat, StrictInt]] = 0.0
    similarity_score: Optional[Union[StrictFloat, StrictInt]] = 0.0
    __properties: ClassVar[List[str]] = ["exercise_id", "related_exercise_id", "weight", "relation_type", "target_concept_id", "shared_concept_ids", "difficulty_gap", "progression_score", "similarity_score"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseRelation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseRelation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exercise_id": obj.get("exercise_id"),
            "related_exercise_id": obj.get("related_exercise_id"),
            "weight": obj.get("weight") if obj.get("weight") is not None else 1.0,
            "relation_type": obj.get("relation_type") if obj.get("relation_type") is not None else '',
            "target_concept_id": obj.get("target_concept_id") if obj.get("target_concept_id") is not None else '',
            "shared_concept_ids": obj.get("shared_concept_ids"),
            "difficulty_gap": obj.get("difficulty_gap") if obj.get("difficulty_gap") is not None else 0.0,
            "progression_score": obj.get("progression_score") if obj.get("progression_score") is not None else 0.0,
            "similarity_score": obj.get("similarity_score") if obj.get("similarity_score") is not None else 0.0
        })
        return _obj


