# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from code_review_ai_client.models.concept_record import ConceptRecord
from code_review_ai_client.models.concept_relation import ConceptRelation
from code_review_ai_client.models.exercise_concept_link import ExerciseConceptLink
from code_review_ai_client.models.exercise_path_link import ExercisePathLink
from code_review_ai_client.models.exercise_record import ExerciseRecord
from code_review_ai_client.models.exercise_relation import ExerciseRelation
from code_review_ai_client.models.review_record import ReviewRecord
from code_review_ai_client.models.review_relation import ReviewRelation
from code_review_ai_client.models.student_record import StudentRecord
from code_review_ai_client.models.submission_record import SubmissionRecord
from code_review_ai_client.models.submission_relation import SubmissionRelation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KnowledgeGraphDocument(BaseModel):
    """
    KnowledgeGraphDocument
    """ # noqa: E501
    concepts: Optional[List[ConceptRecord]] = None
    concept_relations: Optional[List[ConceptRelation]] = None
    exercises: Optional[List[ExerciseRecord]] = None
    exercise_concept_links: Optional[List[ExerciseConceptLink]] = None
    exercise_path_links: Optional[List[ExercisePathLink]] = None
    exercise_relations: Optional[List[ExerciseRelation]] = None
    students: Optional[List[StudentRecord]] = None
    submissions: Optional[List[SubmissionRecord]] = None
    submission_relations: Optional[List[SubmissionRelation]] = None
    reviews: Optional[List[ReviewRecord]] = None
    review_relations: Optional[List[ReviewRelation]] = None
    __properties: ClassVar[List[str]] = ["concepts", "concept_relations", "exercises", "exercise_concept_links", "exercise_path_links", "exercise_relations", "students", "submissions", "submission_relations", "reviews", "review_relations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KnowledgeGraphDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in concepts (list)
        _items = []
        if self.concepts:
            for _item_concepts in self.concepts:
                if _item_concepts:
                    _items.append(_item_concepts.to_dict())
            _dict['concepts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in concept_relations (list)
        _items = []
        if self.concept_relations:
            for _item_concept_relations in self.concept_relations:
                if _item_concept_relations:
                    _items.append(_item_concept_relations.to_dict())
            _dict['concept_relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exercises (list)
        _items = []
        if self.exercises:
            for _item_exercises in self.exercises:
                if _item_exercises:
                    _items.append(_item_exercises.to_dict())
            _dict['exercises'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exercise_concept_links (list)
        _items = []
        if self.exercise_concept_links:
            for _item_exercise_concept_links in self.exercise_concept_links:
                if _item_exercise_concept_links:
                    _items.append(_item_exercise_concept_links.to_dict())
            _dict['exercise_concept_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exercise_path_links (list)
        _items = []
        if self.exercise_path_links:
            for _item_exercise_path_links in self.exercise_path_links:
                if _item_exercise_path_links:
                    _items.append(_item_exercise_path_links.to_dict())
            _dict['exercise_path_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exercise_relations (list)
        _items = []
        if self.exercise_relations:
            for _item_exercise_relations in self.exercise_relations:
                if _item_exercise_relations:
                    _items.append(_item_exercise_relations.to_dict())
            _dict['exercise_relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in students (list)
        _items = []
        if self.students:
            for _item_students in self.students:
                if _item_students:
                    _items.append(_item_students.to_dict())
            _dict['students'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in submissions (list)
        _items = []
        if self.submissions:
            for _item_submissions in self.submissions:
                if _item_submissions:
                    _items.append(_item_submissions.to_dict())
            _dict['submissions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in submission_relations (list)
        _items = []
        if self.submission_relations:
            for _item_submission_relations in self.submission_relations:
                if _item_submission_relations:
                    _items.append(_item_submission_relations.to_dict())
            _dict['submission_relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reviews (list)
        _items = []
        if self.reviews:
            for _item_reviews in self.reviews:
                if _item_reviews:
                    _items.append(_item_reviews.to_dict())
            _dict['reviews'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in review_relations (list)
        _items = []
        if self.review_relations:
            for _item_review_relations in self.review_relations:
                if _item_review_relations:
                    _items.append(_item_review_relations.to_dict())
            _dict['review_relations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KnowledgeGraphDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "concepts": [ConceptRecord.from_dict(_item) for _item in obj["concepts"]] if obj.get("concepts") is not None else None,
            "concept_relations": [ConceptRelation.from_dict(_item) for _item in obj["concept_relations"]] if obj.get("concept_relations") is not None else None,
            "exercises": [ExerciseRecord.from_dict(_item) for _item in obj["exercises"]] if obj.get("exercises") is not None else None,
            "exercise_concept_links": [ExerciseConceptLink.from_dict(_item) for _item in obj["exercise_concept_links"]] if obj.get("exercise_concept_links") is not None else None,
            "exercise_path_links": [ExercisePathLink.from_dict(_item) for _item in obj["exercise_path_links"]] if obj.get("exercise_path_links") is not None else None,
            "exercise_relations": [ExerciseRelation.from_dict(_item) for _item in obj["exercise_relations"]] if obj.get("exercise_relations") is not None else None,
            "students": [StudentRecord.from_dict(_item) for _item in obj["students"]] if obj.get("students") is not None else None,
            "submissions": [SubmissionRecord.from_dict(_item) for _item in obj["submissions"]] if obj.get("submissions") is not None else None,
            "submission_relations": [SubmissionRelation.from_dict(_item) for _item in obj["submission_relations"]] if obj.get("submission_relations") is not None else None,
            "reviews": [ReviewRecord.from_dict(_item) for _item in obj["reviews"]] if obj.get("reviews") is not None else None,
            "review_relations": [ReviewRelation.from_dict(_item) for _item in obj["review_relations"]] if obj.get("review_relations") is not None else None
        })
        return _obj


