# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchExerciseRelationsRequest(BaseModel):
    """
    PatchExerciseRelationsRequest
    """ # noqa: E501
    concept_slugs: Optional[List[StrictStr]] = None
    related_exercise_slugs: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["concept_slugs", "related_exercise_slugs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchExerciseRelationsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if concept_slugs (nullable) is None
        # and model_fields_set contains the field
        if self.concept_slugs is None and "concept_slugs" in self.model_fields_set:
            _dict['concept_slugs'] = None

        # set to None if related_exercise_slugs (nullable) is None
        # and model_fields_set contains the field
        if self.related_exercise_slugs is None and "related_exercise_slugs" in self.model_fields_set:
            _dict['related_exercise_slugs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchExerciseRelationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "concept_slugs": obj.get("concept_slugs"),
            "related_exercise_slugs": obj.get("related_exercise_slugs")
        })
        return _obj


