# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from code_review_ai_client.models.explanation_block import ExplanationBlock
from code_review_ai_client.models.recommendation_graph_summary import RecommendationGraphSummary
from code_review_ai_client.models.recommendation_roadmap_step import RecommendationRoadmapStep
from code_review_ai_client.models.recommendation_scoring_framework import RecommendationScoringFramework
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RecommendationResponse(BaseModel):
    """
    RecommendationResponse
    """ # noqa: E501
    student_id: StrictStr
    current_exercise_id: StrictStr
    anchor_concept: StrictStr
    assigned_path: StrictStr
    focus_concept_id: StrictStr
    critical_errors: StrictInt
    framework: RecommendationScoringFramework
    graph_summary: RecommendationGraphSummary
    reasoning: ExplanationBlock
    roadmap_summary: ExplanationBlock
    roadmap: List[RecommendationRoadmapStep]
    __properties: ClassVar[List[str]] = ["student_id", "current_exercise_id", "anchor_concept", "assigned_path", "focus_concept_id", "critical_errors", "framework", "graph_summary", "reasoning", "roadmap_summary", "roadmap"]

    @field_validator('assigned_path')
    def assigned_path_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['REINFORCE', 'IMPROVE', 'NEXT_CONCEPT']):
            raise ValueError("must be one of enum values ('REINFORCE', 'IMPROVE', 'NEXT_CONCEPT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecommendationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of framework
        if self.framework:
            _dict['framework'] = self.framework.to_dict()
        # override the default output from pydantic by calling `to_dict()` of graph_summary
        if self.graph_summary:
            _dict['graph_summary'] = self.graph_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reasoning
        if self.reasoning:
            _dict['reasoning'] = self.reasoning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of roadmap_summary
        if self.roadmap_summary:
            _dict['roadmap_summary'] = self.roadmap_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in roadmap (list)
        _items = []
        if self.roadmap:
            for _item_roadmap in self.roadmap:
                if _item_roadmap:
                    _items.append(_item_roadmap.to_dict())
            _dict['roadmap'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecommendationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "student_id": obj.get("student_id"),
            "current_exercise_id": obj.get("current_exercise_id"),
            "anchor_concept": obj.get("anchor_concept"),
            "assigned_path": obj.get("assigned_path"),
            "focus_concept_id": obj.get("focus_concept_id"),
            "critical_errors": obj.get("critical_errors"),
            "framework": RecommendationScoringFramework.from_dict(obj["framework"]) if obj.get("framework") is not None else None,
            "graph_summary": RecommendationGraphSummary.from_dict(obj["graph_summary"]) if obj.get("graph_summary") is not None else None,
            "reasoning": ExplanationBlock.from_dict(obj["reasoning"]) if obj.get("reasoning") is not None else None,
            "roadmap_summary": ExplanationBlock.from_dict(obj["roadmap_summary"]) if obj.get("roadmap_summary") is not None else None,
            "roadmap": [RecommendationRoadmapStep.from_dict(_item) for _item in obj["roadmap"]] if obj.get("roadmap") is not None else None
        })
        return _obj


