# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReviewRecord(BaseModel):
    """
    ReviewRecord
    """ # noqa: E501
    review_id: StrictStr
    student_id: StrictStr
    exercise_id: Optional[StrictStr] = ''
    submission_id: Optional[StrictStr] = ''
    current_concept: Optional[StrictStr] = ''
    created_at: Optional[StrictStr] = ''
    summary: StrictStr
    detail: StrictStr
    __properties: ClassVar[List[str]] = ["review_id", "student_id", "exercise_id", "submission_id", "current_concept", "created_at", "summary", "detail"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "review_id": obj.get("review_id"),
            "student_id": obj.get("student_id"),
            "exercise_id": obj.get("exercise_id") if obj.get("exercise_id") is not None else '',
            "submission_id": obj.get("submission_id") if obj.get("submission_id") is not None else '',
            "current_concept": obj.get("current_concept") if obj.get("current_concept") is not None else '',
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else '',
            "summary": obj.get("summary"),
            "detail": obj.get("detail")
        })
        return _obj


