# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from code_review_ai_client.models.column_context import ColumnContext
from code_review_ai_client.models.line_context import LineContext
from code_review_ai_client.models.review_link import ReviewLink
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReviewItem(BaseModel):
    """
    ReviewItem
    """ # noqa: E501
    line: Optional[LineContext] = None
    column: Optional[ColumnContext] = None
    code_snippet: StrictStr
    type: StrictStr
    issue: StrictStr = Field(description="For a 'Warning', this should explain a clean-code, readability, or refactoring improvement in simple terms.")
    fix_suggestion: StrictStr
    review_link: Optional[ReviewLink] = None
    __properties: ClassVar[List[str]] = ["line", "column", "code_snippet", "type", "issue", "fix_suggestion", "review_link"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Error', 'Warning']):
            raise ValueError("must be one of enum values ('Error', 'Warning')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of line
        if self.line:
            _dict['line'] = self.line.to_dict()
        # override the default output from pydantic by calling `to_dict()` of column
        if self.column:
            _dict['column'] = self.column.to_dict()
        # override the default output from pydantic by calling `to_dict()` of review_link
        if self.review_link:
            _dict['review_link'] = self.review_link.to_dict()
        # set to None if column (nullable) is None
        # and model_fields_set contains the field
        if self.column is None and "column" in self.model_fields_set:
            _dict['column'] = None

        # set to None if review_link (nullable) is None
        # and model_fields_set contains the field
        if self.review_link is None and "review_link" in self.model_fields_set:
            _dict['review_link'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "line": LineContext.from_dict(obj["line"]) if obj.get("line") is not None else None,
            "column": ColumnContext.from_dict(obj["column"]) if obj.get("column") is not None else None,
            "code_snippet": obj.get("code_snippet"),
            "type": obj.get("type"),
            "issue": obj.get("issue"),
            "fix_suggestion": obj.get("fix_suggestion"),
            "review_link": ReviewLink.from_dict(obj["review_link"]) if obj.get("review_link") is not None else None
        })
        return _obj


