# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReviewRelation(BaseModel):
    """
    ReviewRelation
    """ # noqa: E501
    previous_review_id: StrictStr
    next_review_id: StrictStr
    student_id: Optional[StrictStr] = ''
    linked_at: Optional[StrictStr] = ''
    same_concept: Optional[StrictBool] = False
    improvement_signal: Optional[Union[StrictFloat, StrictInt]] = 0.0
    severity_change: Optional[Union[StrictFloat, StrictInt]] = 0.0
    __properties: ClassVar[List[str]] = ["previous_review_id", "next_review_id", "student_id", "linked_at", "same_concept", "improvement_signal", "severity_change"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewRelation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewRelation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "previous_review_id": obj.get("previous_review_id"),
            "next_review_id": obj.get("next_review_id"),
            "student_id": obj.get("student_id") if obj.get("student_id") is not None else '',
            "linked_at": obj.get("linked_at") if obj.get("linked_at") is not None else '',
            "same_concept": obj.get("same_concept") if obj.get("same_concept") is not None else False,
            "improvement_signal": obj.get("improvement_signal") if obj.get("improvement_signal") is not None else 0.0,
            "severity_change": obj.get("severity_change") if obj.get("severity_change") is not None else 0.0
        })
        return _obj


