# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReviewLink(BaseModel):
    """
    ReviewLink
    """ # noqa: E501
    previous_submission_id: StrictStr
    previous_code_snippets: Optional[List[StrictStr]] = None
    comparison_mode: Optional[StrictStr] = None
    what_improved: StrictStr
    what_still_needs_work: StrictStr
    relation_summary: StrictStr
    __properties: ClassVar[List[str]] = ["previous_submission_id", "previous_code_snippets", "comparison_mode", "what_improved", "what_still_needs_work", "relation_summary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewLink from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if comparison_mode (nullable) is None
        # and model_fields_set contains the field
        if self.comparison_mode is None and "comparison_mode" in self.model_fields_set:
            _dict['comparison_mode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewLink from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "previous_submission_id": obj.get("previous_submission_id"),
            "previous_code_snippets": obj.get("previous_code_snippets"),
            "comparison_mode": obj.get("comparison_mode"),
            "what_improved": obj.get("what_improved"),
            "what_still_needs_work": obj.get("what_still_needs_work"),
            "relation_summary": obj.get("relation_summary")
        })
        return _obj


