# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from code_review_ai_client.models.score_card_item import ScoreCardItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScoreCard(BaseModel):
    """
    ScoreCard
    """ # noqa: E501
    problem_solving_creativity: ScoreCardItem
    logic_traceability: ScoreCardItem
    generalization_score: ScoreCardItem
    construct_appropriateness: ScoreCardItem
    self_correction_path: ScoreCardItem
    variable_understanding: ScoreCardItem
    control_flow_understanding: ScoreCardItem
    input_output_awareness: ScoreCardItem
    edge_case_awareness: ScoreCardItem
    debugging_readiness: ScoreCardItem
    __properties: ClassVar[List[str]] = ["problem_solving_creativity", "logic_traceability", "generalization_score", "construct_appropriateness", "self_correction_path", "variable_understanding", "control_flow_understanding", "input_output_awareness", "edge_case_awareness", "debugging_readiness"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScoreCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of problem_solving_creativity
        if self.problem_solving_creativity:
            _dict['problem_solving_creativity'] = self.problem_solving_creativity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of logic_traceability
        if self.logic_traceability:
            _dict['logic_traceability'] = self.logic_traceability.to_dict()
        # override the default output from pydantic by calling `to_dict()` of generalization_score
        if self.generalization_score:
            _dict['generalization_score'] = self.generalization_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of construct_appropriateness
        if self.construct_appropriateness:
            _dict['construct_appropriateness'] = self.construct_appropriateness.to_dict()
        # override the default output from pydantic by calling `to_dict()` of self_correction_path
        if self.self_correction_path:
            _dict['self_correction_path'] = self.self_correction_path.to_dict()
        # override the default output from pydantic by calling `to_dict()` of variable_understanding
        if self.variable_understanding:
            _dict['variable_understanding'] = self.variable_understanding.to_dict()
        # override the default output from pydantic by calling `to_dict()` of control_flow_understanding
        if self.control_flow_understanding:
            _dict['control_flow_understanding'] = self.control_flow_understanding.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input_output_awareness
        if self.input_output_awareness:
            _dict['input_output_awareness'] = self.input_output_awareness.to_dict()
        # override the default output from pydantic by calling `to_dict()` of edge_case_awareness
        if self.edge_case_awareness:
            _dict['edge_case_awareness'] = self.edge_case_awareness.to_dict()
        # override the default output from pydantic by calling `to_dict()` of debugging_readiness
        if self.debugging_readiness:
            _dict['debugging_readiness'] = self.debugging_readiness.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScoreCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "problem_solving_creativity": ScoreCardItem.from_dict(obj["problem_solving_creativity"]) if obj.get("problem_solving_creativity") is not None else None,
            "logic_traceability": ScoreCardItem.from_dict(obj["logic_traceability"]) if obj.get("logic_traceability") is not None else None,
            "generalization_score": ScoreCardItem.from_dict(obj["generalization_score"]) if obj.get("generalization_score") is not None else None,
            "construct_appropriateness": ScoreCardItem.from_dict(obj["construct_appropriateness"]) if obj.get("construct_appropriateness") is not None else None,
            "self_correction_path": ScoreCardItem.from_dict(obj["self_correction_path"]) if obj.get("self_correction_path") is not None else None,
            "variable_understanding": ScoreCardItem.from_dict(obj["variable_understanding"]) if obj.get("variable_understanding") is not None else None,
            "control_flow_understanding": ScoreCardItem.from_dict(obj["control_flow_understanding"]) if obj.get("control_flow_understanding") is not None else None,
            "input_output_awareness": ScoreCardItem.from_dict(obj["input_output_awareness"]) if obj.get("input_output_awareness") is not None else None,
            "edge_case_awareness": ScoreCardItem.from_dict(obj["edge_case_awareness"]) if obj.get("edge_case_awareness") is not None else None,
            "debugging_readiness": ScoreCardItem.from_dict(obj["debugging_readiness"]) if obj.get("debugging_readiness") is not None else None
        })
        return _obj


