# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from code_review_ai_client.models.review_item import ReviewItem
from code_review_ai_client.models.score_card import ScoreCard
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpsertReviewRequest(BaseModel):
    """
    UpsertReviewRequest
    """ # noqa: E501
    submission_id: StrictStr
    summary: StrictStr
    detail: StrictStr
    review_items: Optional[List[ReviewItem]] = None
    scorecard: ScoreCard
    current_concept: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["submission_id", "summary", "detail", "review_items", "scorecard", "current_concept"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpsertReviewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in review_items (list)
        _items = []
        if self.review_items:
            for _item_review_items in self.review_items:
                if _item_review_items:
                    _items.append(_item_review_items.to_dict())
            _dict['review_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of scorecard
        if self.scorecard:
            _dict['scorecard'] = self.scorecard.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpsertReviewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "submission_id": obj.get("submission_id"),
            "summary": obj.get("summary"),
            "detail": obj.get("detail"),
            "review_items": [ReviewItem.from_dict(_item) for _item in obj["review_items"]] if obj.get("review_items") is not None else None,
            "scorecard": ScoreCard.from_dict(obj["scorecard"]) if obj.get("scorecard") is not None else None,
            "current_concept": obj.get("current_concept") if obj.get("current_concept") is not None else ''
        })
        return _obj


