# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from code_review_ai_client.models.submission_test_case_output import SubmissionTestCaseOutput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpsertSubmissionRequest(BaseModel):
    """
    UpsertSubmissionRequest
    """ # noqa: E501
    student_id: StrictStr
    exercise_id: StrictStr
    code: StrictStr
    testcase_outputs: Optional[List[SubmissionTestCaseOutput]] = None
    __properties: ClassVar[List[str]] = ["student_id", "exercise_id", "code", "testcase_outputs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpsertSubmissionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in testcase_outputs (list)
        _items = []
        if self.testcase_outputs:
            for _item_testcase_outputs in self.testcase_outputs:
                if _item_testcase_outputs:
                    _items.append(_item_testcase_outputs.to_dict())
            _dict['testcase_outputs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpsertSubmissionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "student_id": obj.get("student_id"),
            "exercise_id": obj.get("exercise_id"),
            "code": obj.get("code"),
            "testcase_outputs": [SubmissionTestCaseOutput.from_dict(_item) for _item in obj["testcase_outputs"]] if obj.get("testcase_outputs") is not None else None
        })
        return _obj


