from typing import List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class TestResult(BaseModel):
    testcase_id: UUID
    name: str
    status: str
    input: str
    expect: str
    actual: str


class AssignmentContext(BaseModel):
    content: str
    language: str = Field(..., description="E.g., C, C++, Python")
    expected_concepts: List[str] = Field(
        default_factory=list,
        description="List of CS concepts expected to be demonstrated",
    )


class Submission(BaseModel):
    code: str


class SubmissionHistoryItem(BaseModel):
    code: str
    failed_test_case_ids: List[UUID] = Field(
        default_factory=list,
        description="UUIDs of the failed testcases for that submission attempt",
    )


class ReviewRequest(BaseModel):
    """The complete input payload for the code review endpoint."""

    assignment: AssignmentContext
    student_submission: Submission
    test_results: List[TestResult]
    history: List[SubmissionHistoryItem] = Field(default_factory=list)


class LineContext(BaseModel):
    start: Optional[int]
    end: Optional[int]


class ColumnContext(BaseModel):
    start: Optional[int]
    end: Optional[int]


class ReviewItem(BaseModel):
    line: LineContext = None
    column: Optional[ColumnContext] = None
    code_snippet: str
    type: Literal["Error", "Warning"]
    issue: str = Field(
        ...,
        description="For a 'Warning', this must describe a case where it can lead to a bug.",
    )
    fix_suggestion: str


class ScoreCardItem(BaseModel):
    score: int = Field(..., ge=1, le=5)
    label: str
    explanation: str


class ScoreCard(BaseModel):
    problem_solving_creativity: ScoreCardItem
    logic_traceability: ScoreCardItem
    generalization_score: ScoreCardItem
    construct_appropriateness: ScoreCardItem
    self_correction_path: ScoreCardItem
    variable_understanding: ScoreCardItem
    control_flow_understanding: ScoreCardItem
    input_output_awareness: ScoreCardItem
    edge_case_awareness: ScoreCardItem
    debugging_readiness: ScoreCardItem


class ReviewResponse(BaseModel):
    """The structured output generated by the Gemini Model."""

    summary: str
    detail: str
    review_items: List[ReviewItem]
    scorecard: ScoreCard
