from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class TestResult(BaseModel):
    name: str
    status: str
    input: str
    expect: str
    actual: str


class AssignmentContext(BaseModel):
    content: str
    language: str = Field(..., description="E.g., C, C++, Python")
    expected_concepts: List[str] = Field(
        default_factory=list,
        description="List of CS concepts expected to be demonstrated",
    )


class Submission(BaseModel):
    code: str


class ReviewRequest(BaseModel):
    """The complete input payload for the code review endpoint."""

    assignment: AssignmentContext
    student_submission: Submission
    test_results: List[TestResult]


# ----------------------------------------------------------------------
# --- 2. Agentic Models (Tool Input/Output) ---
# ----------------------------------------------------------------------


# ----------------------------------------------------------------------
# --- 3. Review Response Models (Final Output) ---
# ----------------------------------------------------------------------


class LineContext(BaseModel):
    start: Optional[int]
    end: Optional[int]


class ColumnContext(BaseModel):
    start: Optional[int]
    end: Optional[int]


class ReviewItem(BaseModel):
    line: LineContext = None
    column: Optional[ColumnContext] = None
    code_snippet: str
    type: Literal["Error", "Warning"]
    issue: str = Field(
        ...,
        description="For a 'Warning', this must describe a case where it can lead to a bug.",
    )
    fix_suggestion: str


class ReviewResponse(BaseModel):
    """The structured output generated by the Gemini Model."""

    summary: str
    detail: str
    review_items: List[ReviewItem]
