# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.explanation_ref import ExplanationRef

class TestExplanationRef(unittest.TestCase):
    """ExplanationRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExplanationRef:
        """Test ExplanationRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExplanationRef`
        """
        model = ExplanationRef()
        if include_optional:
            return ExplanationRef(
                ref_id = '',
                content = '',
                ref_category = 'code'
            )
        else:
            return ExplanationRef(
                ref_id = '',
                content = '',
                ref_category = 'code',
        )
        """

    def testExplanationRef(self):
        """Test ExplanationRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
