# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_generate_recommendation_api_v1_recommendation_post(self) -> None:
        """Test case for generate_recommendation_api_v1_recommendation_post

        Generate Recommendation
        """
        pass

    def test_get_knowledge_graph_snapshot_api_v1_knowledgegraph_get(self) -> None:
        """Test case for get_knowledge_graph_snapshot_api_v1_knowledgegraph_get

        Get Knowledge Graph Snapshot
        """
        pass

    def test_patch_concept_relations_api_v1_knowledgegraph_concepts_concept_slug_relations_patch(self) -> None:
        """Test case for patch_concept_relations_api_v1_knowledgegraph_concepts_concept_slug_relations_patch

        Patch Concept Relations
        """
        pass

    def test_patch_exercise_relations_api_v1_knowledgegraph_exercises_exercise_id_relations_patch(self) -> None:
        """Test case for patch_exercise_relations_api_v1_knowledgegraph_exercises_exercise_id_relations_patch

        Patch Exercise Relations
        """
        pass

    def test_review_code_api_v1_review_code_post(self) -> None:
        """Test case for review_code_api_v1_review_code_post

        Review Code
        """
        pass

    def test_upsert_concept_api_v1_knowledgegraph_concepts_concept_slug_put(self) -> None:
        """Test case for upsert_concept_api_v1_knowledgegraph_concepts_concept_slug_put

        Upsert Concept
        """
        pass

    def test_upsert_exercise_api_v1_knowledgegraph_exercises_exercise_id_put(self) -> None:
        """Test case for upsert_exercise_api_v1_knowledgegraph_exercises_exercise_id_put

        Upsert Exercise
        """
        pass

    def test_upsert_review_api_v1_knowledgegraph_reviews_review_id_put(self) -> None:
        """Test case for upsert_review_api_v1_knowledgegraph_reviews_review_id_put

        Upsert Review
        """
        pass

    def test_upsert_student_api_v1_knowledgegraph_students_student_id_put(self) -> None:
        """Test case for upsert_student_api_v1_knowledgegraph_students_student_id_put

        Upsert Student
        """
        pass

    def test_upsert_submission_api_v1_knowledgegraph_submissions_submission_id_put(self) -> None:
        """Test case for upsert_submission_api_v1_knowledgegraph_submissions_submission_id_put

        Upsert Submission
        """
        pass


if __name__ == '__main__':
    unittest.main()
