# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.recommendation_response import RecommendationResponse

class TestRecommendationResponse(unittest.TestCase):
    """RecommendationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendationResponse:
        """Test RecommendationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendationResponse`
        """
        model = RecommendationResponse()
        if include_optional:
            return RecommendationResponse(
                student_id = '',
                current_exercise_id = '',
                anchor_concept = '',
                assigned_path = 'REINFORCE',
                focus_concept_id = '',
                critical_errors = 56,
                framework = code_review_ai_client.models.recommendation_scoring_framework.RecommendationScoringFramework(
                    risk_level = 'high', 
                    readiness_level = 'emerging', 
                    explanation = '', ),
                graph_summary = code_review_ai_client.models.recommendation_graph_summary.RecommendationGraphSummary(
                    current_concept_weight = 1.337, 
                    best_path_weight = 1.337, 
                    best_related_exercise_weight = 1.337, 
                    latest_review_improvement_signal = 1.337, 
                    latest_review_severity_change = 1.337, 
                    latest_submission_improvement_ratio = 1.337, 
                    latest_submission_regression_ratio = 1.337, ),
                reasoning = code_review_ai_client.models.explanation_block.ExplanationBlock(
                    content = '', 
                    refs = [
                        code_review_ai_client.models.explanation_ref.ExplanationRef(
                            ref_id = '', 
                            content = '', 
                            ref_category = 'code', )
                        ], ),
                roadmap_summary = code_review_ai_client.models.explanation_block.ExplanationBlock(
                    content = '', 
                    refs = [
                        code_review_ai_client.models.explanation_ref.ExplanationRef(
                            ref_id = '', 
                            content = '', 
                            ref_category = 'code', )
                        ], ),
                roadmap = [
                    code_review_ai_client.models.recommendation_roadmap_step.RecommendationRoadmapStep(
                        step = 56, 
                        exercise = code_review_ai_client.models.recommendation_exercise.RecommendationExercise(
                            exercise_id = '', 
                            slug = '', 
                            title = '', 
                            description = '', 
                            content = '', 
                            difficulty = '', 
                            tags = [
                                ''
                                ], 
                            concept_ids = [
                                ''
                                ], 
                            directive = '', ), )
                    ]
            )
        else:
            return RecommendationResponse(
                student_id = '',
                current_exercise_id = '',
                anchor_concept = '',
                assigned_path = 'REINFORCE',
                focus_concept_id = '',
                critical_errors = 56,
                framework = code_review_ai_client.models.recommendation_scoring_framework.RecommendationScoringFramework(
                    risk_level = 'high', 
                    readiness_level = 'emerging', 
                    explanation = '', ),
                graph_summary = code_review_ai_client.models.recommendation_graph_summary.RecommendationGraphSummary(
                    current_concept_weight = 1.337, 
                    best_path_weight = 1.337, 
                    best_related_exercise_weight = 1.337, 
                    latest_review_improvement_signal = 1.337, 
                    latest_review_severity_change = 1.337, 
                    latest_submission_improvement_ratio = 1.337, 
                    latest_submission_regression_ratio = 1.337, ),
                reasoning = code_review_ai_client.models.explanation_block.ExplanationBlock(
                    content = '', 
                    refs = [
                        code_review_ai_client.models.explanation_ref.ExplanationRef(
                            ref_id = '', 
                            content = '', 
                            ref_category = 'code', )
                        ], ),
                roadmap_summary = code_review_ai_client.models.explanation_block.ExplanationBlock(
                    content = '', 
                    refs = [
                        code_review_ai_client.models.explanation_ref.ExplanationRef(
                            ref_id = '', 
                            content = '', 
                            ref_category = 'code', )
                        ], ),
                roadmap = [
                    code_review_ai_client.models.recommendation_roadmap_step.RecommendationRoadmapStep(
                        step = 56, 
                        exercise = code_review_ai_client.models.recommendation_exercise.RecommendationExercise(
                            exercise_id = '', 
                            slug = '', 
                            title = '', 
                            description = '', 
                            content = '', 
                            difficulty = '', 
                            tags = [
                                ''
                                ], 
                            concept_ids = [
                                ''
                                ], 
                            directive = '', ), )
                    ],
        )
        """

    def testRecommendationResponse(self):
        """Test RecommendationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
