# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.review_item import ReviewItem

class TestReviewItem(unittest.TestCase):
    """ReviewItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewItem:
        """Test ReviewItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewItem`
        """
        model = ReviewItem()
        if include_optional:
            return ReviewItem(
                line = code_review_ai_client.models.line_context.LineContext(
                    start = 56, 
                    end = 56, ),
                column = code_review_ai_client.models.column_context.ColumnContext(
                    start = 56, 
                    end = 56, ),
                code_snippet = '',
                type = 'Error',
                issue = '',
                fix_suggestion = '',
                review_link = code_review_ai_client.models.review_link.ReviewLink(
                    previous_submission_id = '', 
                    previous_code_snippets = [
                        ''
                        ], 
                    comparison_mode = '', 
                    what_improved = '', 
                    what_still_needs_work = '', 
                    relation_summary = '', )
            )
        else:
            return ReviewItem(
                code_snippet = '',
                type = 'Error',
                issue = '',
                fix_suggestion = '',
        )
        """

    def testReviewItem(self):
        """Test ReviewItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
