# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.batch_patch_exercise_relations_request import BatchPatchExerciseRelationsRequest

class TestBatchPatchExerciseRelationsRequest(unittest.TestCase):
    """BatchPatchExerciseRelationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchPatchExerciseRelationsRequest:
        """Test BatchPatchExerciseRelationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchPatchExerciseRelationsRequest`
        """
        model = BatchPatchExerciseRelationsRequest()
        if include_optional:
            return BatchPatchExerciseRelationsRequest(
                exercises = [
                    code_review_ai_client.models.batch_patch_exercise_relations_item.BatchPatchExerciseRelationsItem(
                        concept_slugs = [
                            ''
                            ], 
                        related_exercise_ids = [
                            ''
                            ], 
                        related_exercise_slugs = [
                            ''
                            ], 
                        exercise_id = '', )
                    ]
            )
        else:
            return BatchPatchExerciseRelationsRequest(
        )
        """

    def testBatchPatchExerciseRelationsRequest(self):
        """Test BatchPatchExerciseRelationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
