# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.batch_upsert_exercise_item import BatchUpsertExerciseItem

class TestBatchUpsertExerciseItem(unittest.TestCase):
    """BatchUpsertExerciseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchUpsertExerciseItem:
        """Test BatchUpsertExerciseItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchUpsertExerciseItem`
        """
        model = BatchUpsertExerciseItem()
        if include_optional:
            return BatchUpsertExerciseItem(
                slug = '',
                title = '',
                description = '',
                content = '',
                difficulty = '',
                tags = [
                    ''
                    ],
                exercise_id = ''
            )
        else:
            return BatchUpsertExerciseItem(
                title = '',
                description = '',
                content = '',
                difficulty = '',
                exercise_id = '',
        )
        """

    def testBatchUpsertExerciseItem(self):
        """Test BatchUpsertExerciseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
