# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.upsert_review_request import UpsertReviewRequest

class TestUpsertReviewRequest(unittest.TestCase):
    """UpsertReviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertReviewRequest:
        """Test UpsertReviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertReviewRequest`
        """
        model = UpsertReviewRequest()
        if include_optional:
            return UpsertReviewRequest(
                submission_id = '',
                summary = '',
                detail = '',
                review_items = [
                    code_review_ai_client.models.review_item.ReviewItem(
                        line = code_review_ai_client.models.line_context.LineContext(
                            start = 56, 
                            end = 56, ), 
                        column = null, 
                        code_snippet = '', 
                        type = 'Error', 
                        issue = '', 
                        fix_suggestion = '', 
                        review_link = null, )
                    ],
                scorecard = code_review_ai_client.models.score_card.ScoreCard(
                    problem_solving_creativity = code_review_ai_client.models.score_card_item.ScoreCardItem(
                        score = 1.0, 
                        label = '', 
                        explanation = '', ), 
                    logic_traceability = code_review_ai_client.models.score_card_item.ScoreCardItem(
                        score = 1.0, 
                        label = '', 
                        explanation = '', ), 
                    generalization_score = , 
                    construct_appropriateness = , 
                    self_correction_path = , 
                    variable_understanding = , 
                    control_flow_understanding = , 
                    input_output_awareness = , 
                    edge_case_awareness = , 
                    debugging_readiness = , ),
                current_concept = ''
            )
        else:
            return UpsertReviewRequest(
                submission_id = '',
                summary = '',
                detail = '',
                scorecard = code_review_ai_client.models.score_card.ScoreCard(
                    problem_solving_creativity = code_review_ai_client.models.score_card_item.ScoreCardItem(
                        score = 1.0, 
                        label = '', 
                        explanation = '', ), 
                    logic_traceability = code_review_ai_client.models.score_card_item.ScoreCardItem(
                        score = 1.0, 
                        label = '', 
                        explanation = '', ), 
                    generalization_score = , 
                    construct_appropriateness = , 
                    self_correction_path = , 
                    variable_understanding = , 
                    control_flow_understanding = , 
                    input_output_awareness = , 
                    edge_case_awareness = , 
                    debugging_readiness = , ),
        )
        """

    def testUpsertReviewRequest(self):
        """Test UpsertReviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
