# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.exercise_relation import ExerciseRelation

class TestExerciseRelation(unittest.TestCase):
    """ExerciseRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseRelation:
        """Test ExerciseRelation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseRelation`
        """
        model = ExerciseRelation()
        if include_optional:
            return ExerciseRelation(
                exercise_id = '',
                related_exercise_id = '',
                weight = 1.337,
                relation_type = '',
                target_concept_id = '',
                shared_concept_ids = [
                    ''
                    ],
                difficulty_gap = 1.337,
                progression_score = 1.337,
                similarity_score = 1.337
            )
        else:
            return ExerciseRelation(
                exercise_id = '',
                related_exercise_id = '',
        )
        """

    def testExerciseRelation(self):
        """Test ExerciseRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
