# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.review_request import ReviewRequest

class TestReviewRequest(unittest.TestCase):
    """ReviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewRequest:
        """Test ReviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewRequest`
        """
        model = ReviewRequest()
        if include_optional:
            return ReviewRequest(
                assignment = code_review_ai_client.models.assignment_context.AssignmentContext(
                    content = '', 
                    language = '', ),
                code = '',
                test_results = [
                    code_review_ai_client.models.test_result.TestResult(
                        testcase_id = '', 
                        name = '', 
                        input = '', 
                        expect = '', 
                        actual = '', )
                    ],
                history = [
                    code_review_ai_client.models.submission_history_item.SubmissionHistoryItem(
                        submission_id = '', 
                        code = '', 
                        failed_test_case_ids = [
                            ''
                            ], 
                        passed_test_case_ids = [
                            ''
                            ], )
                    ]
            )
        else:
            return ReviewRequest(
                assignment = code_review_ai_client.models.assignment_context.AssignmentContext(
                    content = '', 
                    language = '', ),
                code = '',
                test_results = [
                    code_review_ai_client.models.test_result.TestResult(
                        testcase_id = '', 
                        name = '', 
                        input = '', 
                        expect = '', 
                        actual = '', )
                    ],
        )
        """

    def testReviewRequest(self):
        """Test ReviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
