# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.upsert_student_profile_request import UpsertStudentProfileRequest

class TestUpsertStudentProfileRequest(unittest.TestCase):
    """UpsertStudentProfileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertStudentProfileRequest:
        """Test UpsertStudentProfileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertStudentProfileRequest`
        """
        model = UpsertStudentProfileRequest()
        if include_optional:
            return UpsertStudentProfileRequest(
                student_profile = code_review_ai_client.models.student_profile_scoring.StudentProfileScoring(
                    concept_mastery = 0.0, 
                    implementation_consistency = 0.0, 
                    debugging_independence = 0.0, 
                    efficiency_awareness = 0.0, 
                    concept_transfer = 0.0, 
                    learning_velocity = 0.0, 
                    notes = '', )
            )
        else:
            return UpsertStudentProfileRequest(
                student_profile = code_review_ai_client.models.student_profile_scoring.StudentProfileScoring(
                    concept_mastery = 0.0, 
                    implementation_consistency = 0.0, 
                    debugging_independence = 0.0, 
                    efficiency_awareness = 0.0, 
                    concept_transfer = 0.0, 
                    learning_velocity = 0.0, 
                    notes = '', ),
        )
        """

    def testUpsertStudentProfileRequest(self):
        """Test UpsertStudentProfileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
