# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.knowledge_graph_snapshot_response import KnowledgeGraphSnapshotResponse

class TestKnowledgeGraphSnapshotResponse(unittest.TestCase):
    """KnowledgeGraphSnapshotResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeGraphSnapshotResponse:
        """Test KnowledgeGraphSnapshotResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeGraphSnapshotResponse`
        """
        model = KnowledgeGraphSnapshotResponse()
        if include_optional:
            return KnowledgeGraphSnapshotResponse(
                graph = code_review_ai_client.models.knowledge_graph_document.KnowledgeGraphDocument(
                    concepts = [
                        code_review_ai_client.models.concept_record.ConceptRecord(
                            concept_id = '', 
                            slug = '', 
                            name = '', 
                            description = '', 
                            difficulty = 56, )
                        ], 
                    concept_relations = [
                        code_review_ai_client.models.concept_relation.ConceptRelation(
                            prerequisite_id = '', 
                            concept_id = '', 
                            strength = 1.337, )
                        ], 
                    exercises = [
                        code_review_ai_client.models.exercise_record.ExerciseRecord(
                            exercise_id = '', 
                            slug = '', 
                            title = '', 
                            description = '', 
                            content = '', 
                            difficulty = '', 
                            tags = [
                                ''
                                ], )
                        ], 
                    exercise_concept_links = [
                        code_review_ai_client.models.exercise_concept_link.ExerciseConceptLink(
                            exercise_id = '', 
                            concept_id = '', 
                            weight = 1.337, )
                        ], 
                    exercise_path_links = [
                        code_review_ai_client.models.exercise_path_link.ExercisePathLink(
                            exercise_id = '', 
                            concept_id = '', 
                            path = 'REINFORCE', 
                            weight = 1.337, )
                        ], 
                    exercise_relations = [
                        code_review_ai_client.models.exercise_relation.ExerciseRelation(
                            exercise_id = '', 
                            related_exercise_id = '', 
                            weight = 1.337, 
                            relation_type = '', 
                            target_concept_id = '', 
                            shared_concept_ids = [
                                ''
                                ], 
                            difficulty_gap = 1.337, 
                            progression_score = 1.337, 
                            similarity_score = 1.337, )
                        ], 
                    students = [
                        code_review_ai_client.models.student_record.StudentRecord(
                            student_id = '', 
                            current_concept = '', 
                            notes = '', )
                        ], 
                    submissions = [
                        code_review_ai_client.models.submission_record.SubmissionRecord(
                            submission_id = '', 
                            student_id = '', 
                            exercise_id = '', 
                            code = '', 
                            testcase_outputs = [
                                code_review_ai_client.models.submission_test_case_output.SubmissionTestCaseOutput(
                                    expect = '', 
                                    output = '', )
                                ], 
                            created_at = '', )
                        ], 
                    submission_relations = [
                        code_review_ai_client.models.submission_relation.SubmissionRelation(
                            previous_submission_id = '', 
                            next_submission_id = '', 
                            student_id = '', 
                            linked_at = '', 
                            same_exercise = True, 
                            improvement_ratio = 1.337, 
                            regression_ratio = 1.337, )
                        ], 
                    reviews = [
                        code_review_ai_client.models.review_record.ReviewRecord(
                            review_id = '', 
                            student_id = '', 
                            exercise_id = '', 
                            submission_id = '', 
                            current_concept = '', 
                            created_at = '', 
                            summary = '', 
                            detail = '', )
                        ], 
                    review_relations = [
                        code_review_ai_client.models.review_relation.ReviewRelation(
                            previous_review_id = '', 
                            next_review_id = '', 
                            student_id = '', 
                            linked_at = '', 
                            same_concept = True, 
                            improvement_signal = 1.337, 
                            severity_change = 1.337, )
                        ], )
            )
        else:
            return KnowledgeGraphSnapshotResponse(
                graph = code_review_ai_client.models.knowledge_graph_document.KnowledgeGraphDocument(
                    concepts = [
                        code_review_ai_client.models.concept_record.ConceptRecord(
                            concept_id = '', 
                            slug = '', 
                            name = '', 
                            description = '', 
                            difficulty = 56, )
                        ], 
                    concept_relations = [
                        code_review_ai_client.models.concept_relation.ConceptRelation(
                            prerequisite_id = '', 
                            concept_id = '', 
                            strength = 1.337, )
                        ], 
                    exercises = [
                        code_review_ai_client.models.exercise_record.ExerciseRecord(
                            exercise_id = '', 
                            slug = '', 
                            title = '', 
                            description = '', 
                            content = '', 
                            difficulty = '', 
                            tags = [
                                ''
                                ], )
                        ], 
                    exercise_concept_links = [
                        code_review_ai_client.models.exercise_concept_link.ExerciseConceptLink(
                            exercise_id = '', 
                            concept_id = '', 
                            weight = 1.337, )
                        ], 
                    exercise_path_links = [
                        code_review_ai_client.models.exercise_path_link.ExercisePathLink(
                            exercise_id = '', 
                            concept_id = '', 
                            path = 'REINFORCE', 
                            weight = 1.337, )
                        ], 
                    exercise_relations = [
                        code_review_ai_client.models.exercise_relation.ExerciseRelation(
                            exercise_id = '', 
                            related_exercise_id = '', 
                            weight = 1.337, 
                            relation_type = '', 
                            target_concept_id = '', 
                            shared_concept_ids = [
                                ''
                                ], 
                            difficulty_gap = 1.337, 
                            progression_score = 1.337, 
                            similarity_score = 1.337, )
                        ], 
                    students = [
                        code_review_ai_client.models.student_record.StudentRecord(
                            student_id = '', 
                            current_concept = '', 
                            notes = '', )
                        ], 
                    submissions = [
                        code_review_ai_client.models.submission_record.SubmissionRecord(
                            submission_id = '', 
                            student_id = '', 
                            exercise_id = '', 
                            code = '', 
                            testcase_outputs = [
                                code_review_ai_client.models.submission_test_case_output.SubmissionTestCaseOutput(
                                    expect = '', 
                                    output = '', )
                                ], 
                            created_at = '', )
                        ], 
                    submission_relations = [
                        code_review_ai_client.models.submission_relation.SubmissionRelation(
                            previous_submission_id = '', 
                            next_submission_id = '', 
                            student_id = '', 
                            linked_at = '', 
                            same_exercise = True, 
                            improvement_ratio = 1.337, 
                            regression_ratio = 1.337, )
                        ], 
                    reviews = [
                        code_review_ai_client.models.review_record.ReviewRecord(
                            review_id = '', 
                            student_id = '', 
                            exercise_id = '', 
                            submission_id = '', 
                            current_concept = '', 
                            created_at = '', 
                            summary = '', 
                            detail = '', )
                        ], 
                    review_relations = [
                        code_review_ai_client.models.review_relation.ReviewRelation(
                            previous_review_id = '', 
                            next_review_id = '', 
                            student_id = '', 
                            linked_at = '', 
                            same_concept = True, 
                            improvement_signal = 1.337, 
                            severity_change = 1.337, )
                        ], ),
        )
        """

    def testKnowledgeGraphSnapshotResponse(self):
        """Test KnowledgeGraphSnapshotResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
