# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.knowledge_graph_submission_response import KnowledgeGraphSubmissionResponse

class TestKnowledgeGraphSubmissionResponse(unittest.TestCase):
    """KnowledgeGraphSubmissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeGraphSubmissionResponse:
        """Test KnowledgeGraphSubmissionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeGraphSubmissionResponse`
        """
        model = KnowledgeGraphSubmissionResponse()
        if include_optional:
            return KnowledgeGraphSubmissionResponse(
                submission = code_review_ai_client.models.submission_record.SubmissionRecord(
                    submission_id = '', 
                    student_id = '', 
                    exercise_id = '', 
                    code = '', 
                    testcase_outputs = [
                        code_review_ai_client.models.submission_test_case_output.SubmissionTestCaseOutput(
                            expect = '', 
                            output = '', )
                        ], 
                    created_at = '', )
            )
        else:
            return KnowledgeGraphSubmissionResponse(
                submission = code_review_ai_client.models.submission_record.SubmissionRecord(
                    submission_id = '', 
                    student_id = '', 
                    exercise_id = '', 
                    code = '', 
                    testcase_outputs = [
                        code_review_ai_client.models.submission_test_case_output.SubmissionTestCaseOutput(
                            expect = '', 
                            output = '', )
                        ], 
                    created_at = '', ),
        )
        """

    def testKnowledgeGraphSubmissionResponse(self):
        """Test KnowledgeGraphSubmissionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
