# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.submission_relation import SubmissionRelation

class TestSubmissionRelation(unittest.TestCase):
    """SubmissionRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionRelation:
        """Test SubmissionRelation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionRelation`
        """
        model = SubmissionRelation()
        if include_optional:
            return SubmissionRelation(
                previous_submission_id = '',
                next_submission_id = '',
                student_id = '',
                linked_at = '',
                same_exercise = True,
                improvement_ratio = 1.337,
                regression_ratio = 1.337
            )
        else:
            return SubmissionRelation(
                previous_submission_id = '',
                next_submission_id = '',
        )
        """

    def testSubmissionRelation(self):
        """Test SubmissionRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
