# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.recommendation_graph_summary import RecommendationGraphSummary

class TestRecommendationGraphSummary(unittest.TestCase):
    """RecommendationGraphSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendationGraphSummary:
        """Test RecommendationGraphSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendationGraphSummary`
        """
        model = RecommendationGraphSummary()
        if include_optional:
            return RecommendationGraphSummary(
                current_concept_weight = 1.337,
                best_path_weight = 1.337,
                best_related_exercise_weight = 1.337,
                latest_review_improvement_signal = 1.337,
                latest_review_severity_change = 1.337,
                latest_submission_improvement_ratio = 1.337,
                latest_submission_regression_ratio = 1.337
            )
        else:
            return RecommendationGraphSummary(
                current_concept_weight = 1.337,
                best_path_weight = 1.337,
                best_related_exercise_weight = 1.337,
                latest_review_improvement_signal = 1.337,
                latest_review_severity_change = 1.337,
                latest_submission_improvement_ratio = 1.337,
                latest_submission_regression_ratio = 1.337,
        )
        """

    def testRecommendationGraphSummary(self):
        """Test RecommendationGraphSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
