# coding: utf-8

"""
    CodeReviewAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from code_review_ai_client.models.exercise_path_link import ExercisePathLink

class TestExercisePathLink(unittest.TestCase):
    """ExercisePathLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExercisePathLink:
        """Test ExercisePathLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExercisePathLink`
        """
        model = ExercisePathLink()
        if include_optional:
            return ExercisePathLink(
                exercise_id = '',
                concept_id = '',
                path = 'REINFORCE',
                weight = 1.337
            )
        else:
            return ExercisePathLink(
                exercise_id = '',
                concept_id = '',
                path = 'REINFORCE',
        )
        """

    def testExercisePathLink(self):
        """Test ExercisePathLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
