# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.problem_api import ProblemApi


class TestProblemApi(unittest.TestCase):
    """ProblemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProblemApi()

    def tearDown(self) -> None:
        pass

    def test_create_problem(self) -> None:
        """Test case for create_problem

        Create a new problem
        """
        pass

    def test_get_problem(self) -> None:
        """Test case for get_problem

        Get problem detail
        """
        pass


if __name__ == '__main__':
    unittest.main()
