# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.document_api import DocumentApi


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Upload document (PDF, video, etc.)
        """
        pass

    def test_download(self) -> None:
        """Test case for download

        Download document (inline preview)
        """
        pass

    def test_get_by_topic(self) -> None:
        """Test case for get_by_topic

        Get documents by topic
        """
        pass

    def test_stream(self) -> None:
        """Test case for stream

        Stream video document (supports Range header)
        """
        pass


if __name__ == '__main__':
    unittest.main()
