# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_topic_response import ApiResponseTopicResponse

class TestApiResponseTopicResponse(unittest.TestCase):
    """ApiResponseTopicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseTopicResponse:
        """Test ApiResponseTopicResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseTopicResponse`
        """
        model = ApiResponseTopicResponse()
        if include_optional:
            return ApiResponseTopicResponse(
                success = True,
                message = '',
                data = openapi_client.models.topic_response.TopicResponse(
                    id = '', 
                    class_id = '', 
                    title = '', 
                    description = '', ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseTopicResponse(
        )
        """

    def testApiResponseTopicResponse(self):
        """Test ApiResponseTopicResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
