# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get user by ID
        """
        pass

    def test_me(self) -> None:
        """Test case for me

        Get current user profile
        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        Update current user profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
