# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_review_response import ApiResponseReviewResponse

class TestApiResponseReviewResponse(unittest.TestCase):
    """ApiResponseReviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseReviewResponse:
        """Test ApiResponseReviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseReviewResponse`
        """
        model = ApiResponseReviewResponse()
        if include_optional:
            return ApiResponseReviewResponse(
                success = True,
                message = '',
                data = openapi_client.models.review_response.ReviewResponse(
                    summary = '', 
                    detail = '', 
                    testcase_results = [
                        openapi_client.models.testcase_result.TestcaseResult(
                            index = 56, 
                            input = '', 
                            expected_output = '', 
                            output = '', 
                            error = '', 
                            status = 'ACCEPTED', 
                            runtime = 56, )
                        ], ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseReviewResponse(
        )
        """

    def testApiResponseReviewResponse(self):
        """Test ApiResponseReviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
