# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_submission_response import ApiResponseSubmissionResponse

class TestApiResponseSubmissionResponse(unittest.TestCase):
    """ApiResponseSubmissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseSubmissionResponse:
        """Test ApiResponseSubmissionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseSubmissionResponse`
        """
        model = ApiResponseSubmissionResponse()
        if include_optional:
            return ApiResponseSubmissionResponse(
                success = True,
                message = '',
                data = openapi_client.models.submission_response.SubmissionResponse(
                    id = '', 
                    status = '', 
                    runtime = 56, 
                    passed_testcases = 56, 
                    total_testcases = 56, ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseSubmissionResponse(
        )
        """

    def testApiResponseSubmissionResponse(self):
        """Test ApiResponseSubmissionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
