# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.submission_api import SubmissionApi


class TestSubmissionApi(unittest.TestCase):
    """SubmissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubmissionApi()

    def tearDown(self) -> None:
        pass

    def test_detail(self) -> None:
        """Test case for detail

        Get submission detail
        """
        pass

    def test_get_problem_submissions(self) -> None:
        """Test case for get_problem_submissions

        Get submissions of a problem
        """
        pass

    def test_overview(self) -> None:
        """Test case for overview

        Get current user's submissions overview
        """
        pass

    def test_submit(self) -> None:
        """Test case for submit

        Submit code for a problem
        """
        pass


if __name__ == '__main__':
    unittest.main()
