# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_topic_overview_response import ApiResponseTopicOverviewResponse

class TestApiResponseTopicOverviewResponse(unittest.TestCase):
    """ApiResponseTopicOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseTopicOverviewResponse:
        """Test ApiResponseTopicOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseTopicOverviewResponse`
        """
        model = ApiResponseTopicOverviewResponse()
        if include_optional:
            return ApiResponseTopicOverviewResponse(
                success = True,
                message = '',
                data = openapi_client.models.topic_overview_response.TopicOverviewResponse(
                    ids = [
                        ''
                        ], ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseTopicOverviewResponse(
        )
        """

    def testApiResponseTopicOverviewResponse(self):
        """Test ApiResponseTopicOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
