# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_class_response import ApiResponseClassResponse

class TestApiResponseClassResponse(unittest.TestCase):
    """ApiResponseClassResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseClassResponse:
        """Test ApiResponseClassResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseClassResponse`
        """
        model = ApiResponseClassResponse()
        if include_optional:
            return ApiResponseClassResponse(
                success = True,
                message = '',
                data = openapi_client.models.class_response.ClassResponse(
                    id = '', 
                    name = '', 
                    description = '', 
                    instructor_id = '', 
                    image_url = '', ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseClassResponse(
        )
        """

    def testApiResponseClassResponse(self):
        """Test ApiResponseClassResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
