# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.class_detail_response import ClassDetailResponse

class TestClassDetailResponse(unittest.TestCase):
    """ClassDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassDetailResponse:
        """Test ClassDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassDetailResponse`
        """
        model = ClassDetailResponse()
        if include_optional:
            return ClassDetailResponse(
                name = '',
                instructor_name = '',
                enrolled_students_count = 56,
                created_at = '',
                status = '',
                schedule = '',
                image_url = ''
            )
        else:
            return ClassDetailResponse(
        )
        """

    def testClassDetailResponse(self):
        """Test ClassDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
