# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.class_response import ClassResponse

class TestClassResponse(unittest.TestCase):
    """ClassResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassResponse:
        """Test ClassResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassResponse`
        """
        model = ClassResponse()
        if include_optional:
            return ClassResponse(
                id = '',
                name = '',
                description = '',
                instructor_id = '',
                image_url = ''
            )
        else:
            return ClassResponse(
        )
        """

    def testClassResponse(self):
        """Test ClassResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
