# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.topic_response import TopicResponse

class TestTopicResponse(unittest.TestCase):
    """TopicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TopicResponse:
        """Test TopicResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TopicResponse`
        """
        model = TopicResponse()
        if include_optional:
            return TopicResponse(
                id = '',
                class_id = '',
                title = '',
                description = ''
            )
        else:
            return TopicResponse(
        )
        """

    def testTopicResponse(self):
        """Test TopicResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
