# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.assignment_api import AssignmentApi


class TestAssignmentApi(unittest.TestCase):
    """AssignmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssignmentApi()

    def tearDown(self) -> None:
        pass

    def test_create_assignment(self) -> None:
        """Test case for create_assignment

        Create new assignment
        """
        pass

    def test_get_assignments(self) -> None:
        """Test case for get_assignments

        Get assignments by topicId
        """
        pass


if __name__ == '__main__':
    unittest.main()
