# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_response_user_response import ApiResponseUserResponse

class TestApiResponseUserResponse(unittest.TestCase):
    """ApiResponseUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseUserResponse:
        """Test ApiResponseUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseUserResponse`
        """
        model = ApiResponseUserResponse()
        if include_optional:
            return ApiResponseUserResponse(
                success = True,
                message = '',
                data = openapi_client.models.user_response.UserResponse(
                    id = '', 
                    email = '', 
                    name = '', 
                    picture = '', 
                    role = '', ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiResponseUserResponse(
        )
        """

    def testApiResponseUserResponse(self):
        """Test ApiResponseUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
