# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from code_review_api_client.models.testcase_dto import TestcaseDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LeetCodeImportRequest(BaseModel):
    """
    LeetCodeImportRequest
    """ # noqa: E501
    external_id: Optional[StrictStr] = Field(default=None, alias="externalId")
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    difficulty: Optional[StrictStr] = None
    constraints: Optional[StrictStr] = None
    starter_codes: Optional[Dict[str, StrictStr]] = Field(default=None, alias="starterCodes")
    testcases: Optional[List[TestcaseDto]] = None
    similar_question_ids: Optional[List[StrictStr]] = Field(default=None, alias="similarQuestionIds")
    tags: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["externalId", "title", "description", "difficulty", "constraints", "starterCodes", "testcases", "similarQuestionIds", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LeetCodeImportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in testcases (list)
        _items = []
        if self.testcases:
            for _item_testcases in self.testcases:
                if _item_testcases:
                    _items.append(_item_testcases.to_dict())
            _dict['testcases'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LeetCodeImportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalId": obj.get("externalId"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "difficulty": obj.get("difficulty"),
            "constraints": obj.get("constraints"),
            "starterCodes": obj.get("starterCodes"),
            "testcases": [TestcaseDto.from_dict(_item) for _item in obj["testcases"]] if obj.get("testcases") is not None else None,
            "similarQuestionIds": obj.get("similarQuestionIds"),
            "tags": obj.get("tags")
        })
        return _obj

