# coding: utf-8

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from code_review_api_client.models.testcase_response import TestcaseResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProblemResponse(BaseModel):
    """
    ProblemResponse
    """ # noqa: E501
    id: Optional[UUID] = None
    external_id: Optional[StrictStr] = Field(default=None, alias="externalId")
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    difficulty: Optional[StrictStr] = None
    problem_constraint: Optional[StrictStr] = Field(default=None, alias="problemConstraint")
    type: Optional[StrictStr] = None
    function_skeletons: Optional[Dict[str, StrictStr]] = Field(default=None, alias="functionSkeletons")
    testcases: Optional[List[TestcaseResponse]] = None
    similar_question_ids: Optional[List[StrictStr]] = Field(default=None, alias="similarQuestionIds")
    __properties: ClassVar[List[str]] = ["id", "externalId", "title", "description", "difficulty", "problemConstraint", "type", "functionSkeletons", "testcases", "similarQuestionIds"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['MANUAL', 'LEETCODE']):
            raise ValueError("must be one of enum values ('MANUAL', 'LEETCODE')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProblemResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in testcases (list)
        _items = []
        if self.testcases:
            for _item_testcases in self.testcases:
                if _item_testcases:
                    _items.append(_item_testcases.to_dict())
            _dict['testcases'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProblemResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "externalId": obj.get("externalId"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "difficulty": obj.get("difficulty"),
            "problemConstraint": obj.get("problemConstraint"),
            "type": obj.get("type"),
            "functionSkeletons": obj.get("functionSkeletons"),
            "testcases": [TestcaseResponse.from_dict(_item) for _item in obj["testcases"]] if obj.get("testcases") is not None else None,
            "similarQuestionIds": obj.get("similarQuestionIds")
        })
        return _obj


