server:
  port: 8080
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
  url: "https://bbc-lms.online"

application:
  url: ${APPLICATION_URL}

leetcode:
  api-url: ${LEETCODE_API_URL:http://localhost:8001/api/problems}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /v3/swagger-ui

jobe:
  base-url: ${JOBE_URL}

google:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect_uri: ${GOOGLE_REDIRECT_URI}

review: 
  url: ${REVIEW_AGENT_URL}

recommend:
  url: ${RECOMMEND_AGENT_URL:http://review-agent:8000/api/v1/recommend}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: datn-bucket

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=require&channel_binding=require
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://bbc-lms.online/api/login/oauth2/code/google"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
