# coding: utf-8

# flake8: noqa

"""
    LMS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AssignmentApi",
    "ClassApi",
    "DocumentApi",
    "ExecutionApi",
    "ProblemApi",
    "ReviewApi",
    "SubmissionApi",
    "TestcaseApi",
    "TopicApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddStudentRequest",
    "ApiResponseAssignmentResponse",
    "ApiResponseClassDetailResponse",
    "ApiResponseClassResponse",
    "ApiResponseDocumentResponse",
    "ApiResponseListAssignmentResponse",
    "ApiResponseListClassOverviewResponse",
    "ApiResponseListDocumentResponse",
    "ApiResponseListReviewResponse",
    "ApiResponseListSubmissionOverviewResponse",
    "ApiResponseListTestcaseResponse",
    "ApiResponseObject",
    "ApiResponseProblemResponse",
    "ApiResponseReviewResponse",
    "ApiResponseRunCodeResponse",
    "ApiResponseSubmissionDetailResponse",
    "ApiResponseSubmissionResponse",
    "ApiResponseTestcaseResponse",
    "ApiResponseTopicDetailResponse",
    "ApiResponseTopicOverviewResponse",
    "ApiResponseTopicResponse",
    "ApiResponseUserResponse",
    "AssignmentResponse",
    "ClassDetailResponse",
    "ClassOverviewResponse",
    "ClassResponse",
    "CreateAssignmentRequest",
    "CreateClassRequest",
    "CreateProblemRequest",
    "CreateTestcaseRequest",
    "CreateTopicRequest",
    "DocumentResponse",
    "ProblemRequest",
    "ProblemResponse",
    "ReviewResponse",
    "RunCodeRequest",
    "RunCodeResponse",
    "RunTestcaseRequest",
    "SubmissionDetailResponse",
    "SubmissionOverviewResponse",
    "SubmissionResponse",
    "SubmitCodeRequest",
    "TestcaseRequest",
    "TestcaseResponse",
    "TestcaseResult",
    "TopicDetailResponse",
    "TopicOverviewResponse",
    "TopicResponse",
    "UpdateUserRequest",
    "UserResponse",
]

# import apis into sdk package
from openapi_client.api.assignment_api import AssignmentApi as AssignmentApi
from openapi_client.api.class_api import ClassApi as ClassApi
from openapi_client.api.document_api import DocumentApi as DocumentApi
from openapi_client.api.execution_api import ExecutionApi as ExecutionApi
from openapi_client.api.problem_api import ProblemApi as ProblemApi
from openapi_client.api.review_api import ReviewApi as ReviewApi
from openapi_client.api.submission_api import SubmissionApi as SubmissionApi
from openapi_client.api.testcase_api import TestcaseApi as TestcaseApi
from openapi_client.api.topic_api import TopicApi as TopicApi
from openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_student_request import AddStudentRequest as AddStudentRequest
from openapi_client.models.api_response_assignment_response import ApiResponseAssignmentResponse as ApiResponseAssignmentResponse
from openapi_client.models.api_response_class_detail_response import ApiResponseClassDetailResponse as ApiResponseClassDetailResponse
from openapi_client.models.api_response_class_response import ApiResponseClassResponse as ApiResponseClassResponse
from openapi_client.models.api_response_document_response import ApiResponseDocumentResponse as ApiResponseDocumentResponse
from openapi_client.models.api_response_list_assignment_response import ApiResponseListAssignmentResponse as ApiResponseListAssignmentResponse
from openapi_client.models.api_response_list_class_overview_response import ApiResponseListClassOverviewResponse as ApiResponseListClassOverviewResponse
from openapi_client.models.api_response_list_document_response import ApiResponseListDocumentResponse as ApiResponseListDocumentResponse
from openapi_client.models.api_response_list_review_response import ApiResponseListReviewResponse as ApiResponseListReviewResponse
from openapi_client.models.api_response_list_submission_overview_response import ApiResponseListSubmissionOverviewResponse as ApiResponseListSubmissionOverviewResponse
from openapi_client.models.api_response_list_testcase_response import ApiResponseListTestcaseResponse as ApiResponseListTestcaseResponse
from openapi_client.models.api_response_object import ApiResponseObject as ApiResponseObject
from openapi_client.models.api_response_problem_response import ApiResponseProblemResponse as ApiResponseProblemResponse
from openapi_client.models.api_response_review_response import ApiResponseReviewResponse as ApiResponseReviewResponse
from openapi_client.models.api_response_run_code_response import ApiResponseRunCodeResponse as ApiResponseRunCodeResponse
from openapi_client.models.api_response_submission_detail_response import ApiResponseSubmissionDetailResponse as ApiResponseSubmissionDetailResponse
from openapi_client.models.api_response_submission_response import ApiResponseSubmissionResponse as ApiResponseSubmissionResponse
from openapi_client.models.api_response_testcase_response import ApiResponseTestcaseResponse as ApiResponseTestcaseResponse
from openapi_client.models.api_response_topic_detail_response import ApiResponseTopicDetailResponse as ApiResponseTopicDetailResponse
from openapi_client.models.api_response_topic_overview_response import ApiResponseTopicOverviewResponse as ApiResponseTopicOverviewResponse
from openapi_client.models.api_response_topic_response import ApiResponseTopicResponse as ApiResponseTopicResponse
from openapi_client.models.api_response_user_response import ApiResponseUserResponse as ApiResponseUserResponse
from openapi_client.models.assignment_response import AssignmentResponse as AssignmentResponse
from openapi_client.models.class_detail_response import ClassDetailResponse as ClassDetailResponse
from openapi_client.models.class_overview_response import ClassOverviewResponse as ClassOverviewResponse
from openapi_client.models.class_response import ClassResponse as ClassResponse
from openapi_client.models.create_assignment_request import CreateAssignmentRequest as CreateAssignmentRequest
from openapi_client.models.create_class_request import CreateClassRequest as CreateClassRequest
from openapi_client.models.create_problem_request import CreateProblemRequest as CreateProblemRequest
from openapi_client.models.create_testcase_request import CreateTestcaseRequest as CreateTestcaseRequest
from openapi_client.models.create_topic_request import CreateTopicRequest as CreateTopicRequest
from openapi_client.models.document_response import DocumentResponse as DocumentResponse
from openapi_client.models.problem_request import ProblemRequest as ProblemRequest
from openapi_client.models.problem_response import ProblemResponse as ProblemResponse
from openapi_client.models.review_response import ReviewResponse as ReviewResponse
from openapi_client.models.run_code_request import RunCodeRequest as RunCodeRequest
from openapi_client.models.run_code_response import RunCodeResponse as RunCodeResponse
from openapi_client.models.run_testcase_request import RunTestcaseRequest as RunTestcaseRequest
from openapi_client.models.submission_detail_response import SubmissionDetailResponse as SubmissionDetailResponse
from openapi_client.models.submission_overview_response import SubmissionOverviewResponse as SubmissionOverviewResponse
from openapi_client.models.submission_response import SubmissionResponse as SubmissionResponse
from openapi_client.models.submit_code_request import SubmitCodeRequest as SubmitCodeRequest
from openapi_client.models.testcase_request import TestcaseRequest as TestcaseRequest
from openapi_client.models.testcase_response import TestcaseResponse as TestcaseResponse
from openapi_client.models.testcase_result import TestcaseResult as TestcaseResult
from openapi_client.models.topic_detail_response import TopicDetailResponse as TopicDetailResponse
from openapi_client.models.topic_overview_response import TopicOverviewResponse as TopicOverviewResponse
from openapi_client.models.topic_response import TopicResponse as TopicResponse
from openapi_client.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from openapi_client.models.user_response import UserResponse as UserResponse

